# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: '1.0.0.$(Rev:r)'

trigger:
 branches:
   include:
     - master
     - develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm run coverage
  displayName: 'npm install and build'

## Can't see test results. Check this? https://stackoverflow.com/questions/51720050/how-to-publish-jest-unit-test-results-in-vsts-tests


- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

- script: |
   npm version $(Build.BuildNumber) 
   npm pack
  displayName: 'Package NPM package'

- task: CopyFiles@2
  inputs:
    contents: '*.tgz'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
